### ISSUE TITLE
Can't run the project, getting this issue

### ISSUE THREAD

**Issue by ravisojitra** [cinder92/musety#1]
> The following commands produced analyzer issues:
> 	Analyze Base/RCTModuleMethod.mm
> 	Analyze Modules/RCTUIManager.m
> 	Analyze RCTImageCache.m
> 	Analyze RCTNetInfo.m
> (4 commands with analyzer issues)
> 
> The following build commands failed:
> 	Ld /Users/apex-5/Desktop/ravi/react-native/musety/ios/build/Build/Products/Debug-iphonesimulator/ReactNativeNavigationTests.xctest/ReactNativeNavigationTests normal x86_64
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/musety.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/musety.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> 
> Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/musety.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
>     at checkExecSyncError (child_process.js:601:13)
>     at Object.execFileSync (child_process.js:621:13)
>     at Promise.then (/Users/apex-5/Desktop/ravi/react-native/musety/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
>     at <anonymous>

**Comment by cinder92** [comment]
Hi, please follow this issue https://github.com/wix/react-native-navigation/issues/4691
